language: node_js
node_js:
- 8.5.0
cache: yarn
before_deploy: gulp
deploy:
- provider: releases
  on:
    tags: true
  skip_cleanup: true
  file_glob: true
  file: 'dist/**.js'
  api_key:
    secure: 0YAPvQPlHb+iHOIvPTcJ5ixmwtl1D8e9ggtgzixF25CR5/9+7taIAb2v/eam73i+/1GihNFQdikJHfj2GZoupIfI5PqJ200fZ1dLb+XtOwop0jsnufaCEsFkXtxK7+Ns/Ag2IxqDZ4FJIPkZlRuZjRHbxdFKxOG2cD/ST5m98YXzUoS9qKw6WgMhyF9MuP3JCZLfEvgJSqUtefIMMq7wkzHmovQ1z0D6ENjIxLkIcuGSL/C2R4MuQxBf62jUAQyaXwJpmLV8C5HiWzoaR4lVi3+SJTaKb0EHloAZSe9oFu1607AJDWHlLw4Vb9akSaMhsN1OJaA9Bie5eczVRxM8ZH7CxQnCZjQuIdHU6sm6lEqo0y0qaW5fO2BEhiOKcCj/nwk0ZkF/AY1nfaLubTZCEhJw8MgtSRysvtPxv9awe0/t1uVpBy5H9ekSAVoVhe02oOVj2aTmdFjcC/M3yHXNbwbuARoiguSgGVy5UCTP9cR21ysAmY5w+D7mdMvRdhKtlQnlLWQShWtcHw3VOlLG2hU3FiJbFduei+RCd3XLY/zmwE9rsMXe+DK3hrF0OVmoEnL3C742eSr99zuGpqQJSvsBuXTRIlRvoQoa5esptsLqzTznleuoxqE9M9ognJvyasaLEcCwNdg4ITcD7txQy+o0A7K5UqyMSvTMz6vt/os=
- provider: npm
  on:
    tags: true
  skip_cleanup: true
  email: "mat.a.brown+popcode@gmail.com"
  api_key:
    secure: VLiyNO34pSN+GH9ckYCj/JE/m1Myyd/N1KjCWNe7isWyVzcBXohXEy8rT0jte9dZKfYcVPMZdOQ0Pkhygjc4Nw1jSWJe+Afe58FFgeg1mX3RFP+MllTsLk40vNeL+otej/ntGgwv9cuHB5nitQbb4FRFagUAElI13D1HM7OsaIj76oo1uA+zv1ytT38HImsHMj22e1bL7oZDe3iynwq+NJGSZWUOVO/hji9d582T6Pm5I2JPVrFDBOaBhi94ZX6HH+zZWjsUjQMupG4UQOAqOPtVaVrOEkxr85bcwexs0F1RgGDFvZSDb6tSZHlqHedKEZxGj1W+RXoazAMnsEFdt7UyXMx0BEvbeKCJQ7gVqQlKSdiGhnDuTj/ZGBOikCaU9MnJt/8JMilazAUNXNasNo/JYd5QKj8S6SuKnwvnpLrbM1oLWICB8vZHZm6ZhQ2WzX5Pj7DoE9V9RGgGRjIOD3ZEx0JaN1ytsQQB5siLbcNVTIpcwdfaaMV3ychNLE1EemelIKGWveh4qdGkjxm4q/NqD9uyYBHxGHUPQRuFjOWyi/SVwBHzoMsdgN0fFI4hPPh64HT4XifvglKokyPhf77rvZMAlKeJhqPtU7fhkBOk4yG7vKMeZxFClEZTa8wILH7F7K/JpY2/lMIsqbdnLuKOVs3UuiL4/6xNJqdgI4o=
