language: javascript
node_js:
- 7.6.0
cache: yarn
deploy:
  on:
    tags: true
  provider: npm
  skip_cleanup: true
  api_key:
    secure: VLiyNO34pSN+GH9ckYCj/JE/m1Myyd/N1KjCWNe7isWyVzcBXohXEy8rT0jte9dZKfYcVPMZdOQ0Pkhygjc4Nw1jSWJe+Afe58FFgeg1mX3RFP+MllTsLk40vNeL+otej/ntGgwv9cuHB5nitQbb4FRFagUAElI13D1HM7OsaIj76oo1uA+zv1ytT38HImsHMj22e1bL7oZDe3iynwq+NJGSZWUOVO/hji9d582T6Pm5I2JPVrFDBOaBhi94ZX6HH+zZWjsUjQMupG4UQOAqOPtVaVrOEkxr85bcwexs0F1RgGDFvZSDb6tSZHlqHedKEZxGj1W+RXoazAMnsEFdt7UyXMx0BEvbeKCJQ7gVqQlKSdiGhnDuTj/ZGBOikCaU9MnJt/8JMilazAUNXNasNo/JYd5QKj8S6SuKnwvnpLrbM1oLWICB8vZHZm6ZhQ2WzX5Pj7DoE9V9RGgGRjIOD3ZEx0JaN1ytsQQB5siLbcNVTIpcwdfaaMV3ychNLE1EemelIKGWveh4qdGkjxm4q/NqD9uyYBHxGHUPQRuFjOWyi/SVwBHzoMsdgN0fFI4hPPh64HT4XifvglKokyPhf77rvZMAlKeJhqPtU7fhkBOk4yG7vKMeZxFClEZTa8wILH7F7K/JpY2/lMIsqbdnLuKOVs3UuiL4/6xNJqdgI4o=
